Feature/#130 cleaup boilerplate
icapps/flutter-template pull request #131
Opened 2020-12-24 15:07 UTC by vanlooverenkoen

2020-12-24 15:12 UTC, NicolaChimerapps commented
Thanks, will take a look after the holidays

2020-12-28 14:17 UTC, NicolaChimerapps commented
Please also update flutter_test to latest nullsafety release.

2020-12-28 14:54 UTC, NicolaChimerapps requested changes

2020-12-28 14:54 UTC, NicolaChimerapps commented on tool/dart_tool/strip_boilerplate_project.dart
> +      final result = stdin.readLineSync();
Inform the user he needs to enter something...

2020-12-28 14:54 UTC, NicolaChimerapps commented on tool/dart_tool/strip_boilerplate_project.dart
> +void main(List<String> args) {
We need to inform the user of the order in which shells need to be run. It seems for example install_fvm.sh is required before running this.
Alternatively, run the required scripts within these

2020-12-28 14:54 UTC, NicolaChimerapps commented on tool/dart_tool/strip_boilerplate_project.dart
> +    final dynamic output = result.stdout;
Seems like this output is not captured/returned. Failures also just keep running next steps

2021-01-04 09:38 UTC, NicolaChimerapps submitted a review, later dismissed

2021-01-04 10:01 UTC, NicolaChimerapps submitted a review, later dismissed

2021-01-04 10:07 UTC, HannesVDB submitted a review, later dismissed

2021-01-23 14:06 UTC, NicolaChimerapps approved these changes

2021-01-23 14:37 UTC, merged