Feature/#77 obfuscation #134 #135 #136
icapps/flutter-template pull request #137
Opened 2021-01-26 12:48 UTC by ikbendewilliam

2021-01-26 12:49 UTC, ikbendewilliam commented on Gemfile
> +gem 'cocoapods'
This was necessary to run fastlane locally. Not sure if this is needed when building on server

2021-01-27 13:26 UTC, vanlooverenkoen commented on ios/Podfile
> +platform :ios, '9.0'
aah it was this line you were refering to. Not sure if this is needed.

2021-01-27 13:30 UTC, vanlooverenkoen commented
Maybe one general question. Maybe we should add something in the readme.md that obfuscation via fastlane is enabled by default and that the files are stored `./build/debug-info/#{options[:flavor]}` and maybe for jenkins we could add an extra info line what regex should be used for archivig these symbol files.

2021-01-27 13:31 UTC, vanlooverenkoen requested changes
Maybe we should add extra documentation to the readme.md that obfuscation is enabled by default when using fastlane for building. And that the symbol files are stored here `./build/debug-info/#{options[:flavor]}` 

an extra line could be a regex that can be used in jenkins for archiving these symbol files

2021-01-27 13:53 UTC, ikbendewilliam commented on ios/Podfile
> +platform :ios, '9.0'
Nope :-) doesn't seem so

2021-01-27 14:52 UTC, vanlooverenkoen approved these changes

2021-01-27 15:20 UTC, merged