[WIP] Nullsafety migration
icapps/flutter-template pull request #160
Opened 2021-03-06 10:43 UTC by vanlooverenkoen

Fixed #152 
Fixed #159

2021-03-08 13:20 UTC, vanlooverenkoen commented
Biggest problem: 
https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md

2021-03-16 09:13 UTC, NicolaChimerapps requested changes

2021-03-16 09:13 UTC, NicolaChimerapps commented on pubspec.yaml
> +  json_serializable: ^4.0.2
This should not be in dependencies. This is a dev dependency with https://pub.dev/packages/json_annotation/install as the regular dependency.

2021-03-22 08:38 UTC, vanlooverenkoen commented
Fix dio breaking changes

2021-04-08 09:01 UTC, merged