#178 analytics
icapps/flutter-template pull request #223
Opened 2021-12-30 17:24 UTC by jorre127

2021-12-31 08:18 UTC, vanlooverenkoen requested changes

2021-12-31 08:18 UTC, vanlooverenkoen commented on ios/Runner.xcodeproj/project.pbxproj
> +	objectVersion = 50;
what is this exactly? Or why has this changed?

2021-12-31 08:18 UTC, vanlooverenkoen commented on lib/navigator/main_navigator.dart
> +  static final List<NavigatorObserver> _navigatorObservers = [GetIt.I.get<FireBaseAnalyticsRepository>().routeObserver];
add extra formatting with `,`

2021-12-31 08:18 UTC, vanlooverenkoen commented on lib/repository/analytics/firebase_analytics_repository.dart
> +    WidgetsBinding.instance!.addObserver(this);
don't forget to remove the observer in some kind of dispose method

2021-12-31 09:28 UTC, jorre127 commented on ios/Runner.xcodeproj/project.pbxproj
> +	objectVersion = 50;
Da is blijkbaar een indicator van u project versie. ObjectVersion 50 Is compatible vanaf Xcode 9.3

2022-01-06 15:36 UTC, NicolaVerbeeck approved these changes

2022-01-06 16:03 UTC, vanlooverenkoen approved these changes

2022-01-06 16:03 UTC, merged