#240: always use fvm in scripts
icapps/flutter-template pull request #244
Opened 2022-04-06 17:40 UTC by vanlooverenkoen

2022-04-06 18:06 UTC, NicolaVerbeeck approved these changes

2022-04-07 07:24 UTC, ikbendewilliam approved these changes

2022-04-07 07:31 UTC, ikbendewilliam commented
See issue #240, not the issue that is addressed

2022-04-07 07:31 UTC, ikbendewilliam requested changes
see issue #240

2022-04-07 18:22 UTC, closed without merging