Bugfix/#239 firebase configurator script
icapps/flutter-template pull request #255
Opened 2022-04-06 20:25 UTC by vanlooverenkoen

Fixed #239

2022-04-07 06:23 UTC, NicolaVerbeeck commented on tool/dart_tool/firebase_configurator.dart
> +  _removeLineInFileStartWith('ios/Runner.xcodeproj/project.pbxproj', "		3629EB6826E758C500F774E2 /* GoogleService-Info-dev.plist in Resources */ = {isa = PBXBuildFile; fileRef = 3629EB6726E758C500F77
This feels like it will break due to changing file refs

2022-04-07 06:24 UTC, NicolaVerbeeck requested changes
The replacement of the files in xcode is not configuration change safe I think

2022-04-07 07:25 UTC, ikbendewilliam commented on tool/rename_project.sh
> +dart pub run tool/dart_tool/rename_project.dart
merge conflict with use fvm branch

2022-08-22 15:47 UTC, NicolaVerbeeck commented
Any updates on this?

2022-08-23 06:33 UTC, vanlooverenkoen commented
We will wait on the flutter_template refactor. And see what we decide there.

2022-10-12 09:55 UTC, vanlooverenkoen commented
Won't use this

2022-10-12 09:55 UTC, closed without merging