Refactor theme to be registered in getIt
icapps/flutter-template pull request #272
Opened 2022-10-13 15:30 UTC by rwillemsandroid

- Refactor theme
- update light mode primary color
- update goldens

2022-10-17 07:52 UTC, vanlooverenkoen requested changes

2022-10-17 07:52 UTC, vanlooverenkoen commented on lib/main_common.dart
> +    themeMode = (brightness == Brightness.dark) ? ThemeMode.dark : ThemeMode.light;
What happens if you change the brightness when the app is open?

2022-10-17 07:52 UTC, vanlooverenkoen commented on lib/repository/shared_prefs/local/local_storage.dart
> -    return theme ?? ThemeMode.system;
instantly return.

2022-10-17 07:52 UTC, vanlooverenkoen commented on lib/screen/login/login_screen.dart
> +          isDarkStyle: (theme.flutterTemplateThemeStyle == FlutterTemplateThemeStyle.dark),
I would create a getter. theme.isDark & theme.isLight

2022-10-17 07:52 UTC, vanlooverenkoen commented on lib/util/extension/theme_extensions.dart
> +  FlutterTemplateTheme get theme => GetIt.I();
Discussed with jordy & nicola. we will move away from GetIt.I() because just like .of(context) we need to do a map lookup. And that is something we don't want

2022-10-17 07:59 UTC, NicolaVerbeeck requested changes

2022-10-17 07:59 UTC, NicolaVerbeeck commented on lib/architecture.dart
> +T _getTheme<T>(BuildContext context) => GetIt.I.get<FlutterTemplateTheme>() as T;
use getIt instance instead of GetIt.I

2022-10-17 07:59 UTC, NicolaVerbeeck commented on lib/di/injectable.dart
> +  Brightness brightness() => MediaQueryData.fromWindow(WidgetsBinding.instance.window).platformBrightness;
Technically not a singleton

2022-10-17 07:59 UTC, NicolaVerbeeck commented on lib/main_common.dart
> +  final flutterTemplateTheme = GetIt.I<FlutterTemplateTheme>();
Use getIt instance instead of GetIt.I

2022-10-17 07:59 UTC, NicolaVerbeeck commented on lib/main_common.dart
> +  final localStorage = GetIt.I<LocalStorage>();
For apps that don't support dynamic themeing, this should be collapsed quicker instead of doing system calls (read preferences)

2022-10-17 07:59 UTC, NicolaVerbeeck commented on lib/screen/login/login_screen.dart
> +          isDarkStyle: (theme.flutterTemplateThemeStyle == FlutterTemplateThemeStyle.dark),
Add convenience getter isDark

2022-10-17 07:59 UTC, NicolaVerbeeck commented on lib/styles/theme_data.dart
> +  FlutterTemplateThemeStyle flutterTemplateThemeStyle = FlutterTemplateThemeStyle.light;
Why is this property mutable?

2022-10-17 07:59 UTC, NicolaVerbeeck commented on lib/util/extension/theme_extensions.dart
> +  FlutterTemplateTheme get theme => GetIt.I();
Use getIt instance instead of GetIt.I

2022-10-17 07:59 UTC, NicolaVerbeeck commented on lib/viewmodel/global/global_viewmodel.dart
> +    notifyListeners();
Don't notify listeners without checking if we are disposed or not

2022-10-17 15:05 UTC, rwillemsandroid commented on lib/styles/theme_data.dart
> +  FlutterTemplateThemeStyle flutterTemplateThemeStyle = FlutterTemplateThemeStyle.light;
because it's set in configureForThemeStyle

2022-10-17 15:08 UTC, rwillemsandroid commented on lib/main_common.dart
> +    themeMode = (brightness == Brightness.dark) ? ThemeMode.dark : ThemeMode.light;
Worked on android due to a strange reboot, now fixed on iOS aswell. 

Side effect is that we have to wrap our tree with a new widget to listen for changes in mediaquery.

2022-10-18 07:23 UTC, NicolaVerbeeck approved these changes

2022-10-20 08:46 UTC, vanlooverenkoen approved these changes

2022-10-20 08:46 UTC, merged