242 we should also have a permission screen that request permission to collect crash reports to match gdpr compliance
icapps/flutter-template pull request #275
Opened 2022-10-19 12:58 UTC by rwillemsandroid

fixes #242

2022-10-19 13:05 UTC, NicolaVerbeeck requested changes
Same help file, no need to duplicate.
Also add screenshot tests for phone and tablet

2022-10-20 08:49 UTC, vanlooverenkoen commented
Fix some merge conflicts

2022-10-21 12:14 UTC, NicolaVerbeeck commented on test/widget/debug/select_language_dialog_test.dart
> +    // when(globalViewModel.isLanguageSelected('en')).thenAnswer((_) => true);
Test gone?

2022-10-21 12:15 UTC, NicolaVerbeeck approved these changes

2022-10-21 12:49 UTC, rwillemsandroid commented on test/widget/debug/select_language_dialog_test.dart
> +    // when(globalViewModel.isLanguageSelected('en')).thenAnswer((_) => true);
hmm, no sure how that happened, restored 👍

2022-10-24 09:22 UTC, merged