Feature/use route generator
icapps/flutter-template pull request #286
Opened 2023-01-10 14:54 UTC by ikbendewilliam

2023-01-16 08:48 UTC, vanlooverenkoen requested changes

2023-01-16 08:48 UTC, vanlooverenkoen commented on lib/main_common.dart
> +    final brightness = getIt.get<Brightness>(); // TODO: Brightness can't be injected
fix todo

2023-01-16 08:48 UTC, vanlooverenkoen commented on lib/screen/login/login_screen.dart
> +  middlewares: [LoginGuard],
formatting

2023-01-16 08:48 UTC, vanlooverenkoen commented on lib/navigator/main_navigator.get_x_navigator.dart
> +  static const homeScreen = '/HomeScreen';
hmm I don't want to be using this. Because these URLs are the ones you will use in web as well. Is it possible to do this in a better way?

2023-01-16 08:48 UTC, vanlooverenkoen commented on lib/navigator/main_navigator.get_x_navigator.dart
> +import '../screen/license/license_screen.dart' as _i7;
package imports?

2023-01-16 08:48 UTC, vanlooverenkoen commented on lib/navigator/main_navigator.get_x_navigator.dart
> +  static const homeScreen = '/HomeScreen';
I saw that it was possible to use custom ones. Please update it to the correct ones

2023-01-17 22:17 UTC, ikbendewilliam commented on lib/main_common.dart
> +    final brightness = getIt.get<Brightness>(); // TODO: Brightness can't be injected
This should be done in a separate PR, this is an issue with the Theme without context.

2023-01-17 22:18 UTC, ikbendewilliam commented on lib/navigator/main_navigator.get_x_navigator.dart
> +  static const homeScreen = '/HomeScreen';
I've changed the default url generation to kebab-case

2023-01-17 22:18 UTC, ikbendewilliam commented on lib/navigator/main_navigator.get_x_navigator.dart
> +import '../screen/license/license_screen.dart' as _i7;
This is a generated file, it's not important IMO, but I can look into it if you want

2023-01-30 08:41 UTC, vanlooverenkoen commented on lib/navigator/main_navigator.get_x_navigator.dart
> +import '../screen/license/license_screen.dart' as _i7;
right :D hahaa

2023-01-30 12:14 UTC, ikbendewilliam commented
New PR #289 that does it without conflicts

2023-01-30 12:14 UTC, closed without merging