#291: added extension to themeMode to get name of enum
icapps/flutter-template pull request #300
Opened 2023-08-11 12:31 UTC by jorre127

2023-08-16 07:47 UTC, vanlooverenkoen requested changes

2023-08-16 07:47 UTC, vanlooverenkoen commented on lib/util/extension/theme_mode_extension.dart
> +  String get value {
use `stringValue` as we do with the model_generator

2023-08-17 06:45 UTC, ikbendewilliam requested changes

2023-08-17 06:45 UTC, ikbendewilliam commented on lib/util/extension/theme_mode_extension.dart
> +  String get stringValue {
Use an expression switch

2023-08-17 08:31 UTC, ikbendewilliam approved these changes

2023-08-17 08:33 UTC, vanlooverenkoen approved these changes

2023-08-22 13:07 UTC, merged