#282 update android scripts
icapps/flutter-template pull request #301
Opened 2023-08-11 13:58 UTC by jorre127

2023-08-16 07:48 UTC, vanlooverenkoen requested changes

2023-08-16 07:48 UTC, vanlooverenkoen commented on android/app/google-services.json
do not commit the google-services.json

2023-08-16 07:50 UTC, vanlooverenkoen requested changes

2023-08-16 07:50 UTC, vanlooverenkoen commented on pubspec.yaml
update dio to fix dependabot

https://github.com/icapps/flutter-template/security/dependabot

2023-08-17 06:44 UTC, ikbendewilliam approved these changes

2023-08-17 06:47 UTC, merged