#313: removed getx and added flushbar
icapps/flutter-template pull request #318
Opened 2023-08-22 13:56 UTC by jorre127

fixes #313

2023-08-23 07:26 UTC, vanlooverenkoen requested changes

2023-08-23 07:26 UTC, vanlooverenkoen commented on lib/navigator/main_navigator.dart
> +  void showError(dynamic error) => _errorUtil.showError(error: error, context: navigatorKey.currentContext!);
do not use `navigatorKey.currentContext!` everywhere place this in a separate file. So we can easily change this implementation in the future

2023-08-24 12:56 UTC, vanlooverenkoen submitted a review, later dismissed

2023-08-24 12:56 UTC, vanlooverenkoen commented on lib/navigator/main_navigator.dart
> +  void showError(dynamic error) => _errorUtil.showError(error: error, context: navigatorKey.currentContext!);
Not needed

2023-09-07 09:22 UTC, vanlooverenkoen submitted a review, later dismissed

2023-09-07 10:26 UTC, vanlooverenkoen commented
@jorre127 build failed

2023-09-14 07:17 UTC, ikbendewilliam approved these changes

2023-09-28 12:25 UTC, merged