Feature/#336 base screen
icapps/flutter-template pull request #351
Opened 2024-10-11 11:59 UTC by jorre127

fixes #336

2024-10-16 13:47 UTC, ikbendewilliam requested changes

2024-10-16 13:47 UTC, ikbendewilliam commented on lib/widget/general/simple_screen/base_screen.dart
> +import 'package:flutter/foundation.dart';
rename folder to base_screen instead of simple_screen

2024-10-16 13:47 UTC, ikbendewilliam commented on lib/widget/general/simple_screen/base_screen.dart
> +  final bool useSlivers;
Good idea to add more functionality, we can do even better imo
Add the ability to show an error by having a String and/or a onRetryPressed. But do make the visualisation a separate widget like you do with _content and _header

2024-10-16 13:47 UTC, ikbendewilliam commented on lib/widget/general/simple_screen/base_screen_content.dart
> +        content = CustomScrollView(
just return here

2024-10-16 13:47 UTC, ikbendewilliam commented on lib/widget/general/simple_screen/base_screen_content.dart
> +      } else {
if you return, no need for the `} else {` here

2024-10-16 13:47 UTC, ikbendewilliam commented on lib/widget/general/simple_screen/base_screen_header.dart
> +                ]
Cheeky `,` missing

2025-01-22 10:30 UTC, jorre127 commented on lib/widget/general/simple_screen/base_screen.dart
> +  final bool useSlivers;
Is it ok if i do this in a separate PR? There have been a lot of changes after this including the redesign, so might be better to add this after those are merged (or based upon those branches)

2025-01-22 11:13 UTC, luca-vz approved these changes

2025-01-22 11:43 UTC, ikbendewilliam approved these changes

2025-01-22 13:09 UTC, merged