#74 fixed android v2 embedding + flutter version 1.22
icapps/flutter-template pull request #75
Opened 2020-10-06 15:10 UTC by SuperMonkey1

Fixes #74 
Fixes #70

2020-10-07 09:49 UTC, vanlooverenkoen requested changes

2020-10-07 09:49 UTC, vanlooverenkoen commented on android/app/src/main/AndroidManifest.xml
> +        <meta-data
meta-data should be moved to the bottom of the <application> tag

2020-10-07 09:49 UTC, vanlooverenkoen commented on ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
This file should be added to the git ignore because it is contains information about your ide

2020-10-16 09:01 UTC, SuperMonkey1 commented on ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
zo dan: 
...
    </intent-filter>
        </activity>

        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

...

2020-10-16 10:20 UTC, vanlooverenkoen approved these changes

2020-10-16 10:20 UTC, merged